/*
    UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL
    INF01202 - ALGORITMOS E PROGRAMAÇÃO

    ATIVIDADE PRÁTICA
    TRABALHO FINAL DA DISCIPLINA

    ALUNOS: FELIPE GALLOIS E HENRIQUE CARNIEL DA SILVA
    MATRÍCULAS: 333713 E 335626

    ESTE PROGRAMA É UM JOGO INSPIRADO NO CLÁSSICO DOS ANOS 1980, DANGEROUS
    DAVE, E É PARTE DO TRABALHO FINAL DE AVALIAÇÃO DA DISCIPLINA DE ALGORITMOS
    E PROGRAMAÇÃO DO SEGUNDO SEMESTRE DE 2021.
*/

#ifndef CONSTANTES_H
#define CONSTANTES_H

/* ENUMS */
enum estados {MENU, JOGO, RANKING}; //ENUMERA OS POSSÍVEIS ESTADOS DO PROGRAMA
enum botao {NOVO, CARREGAR, RANK, SAIR}; //ENUMERA OS POSSÍVEIS SELEÇÕES NO MENU INICIAL
enum teclas {INVALIDO, CIMA, BAIXO, DIREITA, ESQUERDA, ESC, S, N, SPCBR, ENTER}; //ENUMERA AS POSSÍVEIS ENTRADAS DO USUÁRIO

/* DEFINES */
#define ESTADOINI MENU //DEFINE EM QUE ESTADO O PROGRAMA DEVE INICIAR

#define ALT_PLACAR 6 //ALTURA DO PLACAR

#define ALTMAX 30 //ALTURA MÁXIMA DE UM MAPA
#define LARGMAX 60 //LARGURA MÁXIMA DE UM MAPA

#define MAPA1 "Mapas/fase_1.txt" //DEFINE O PRIMEIRO MAPA A SER ABERTO

#define DELAY 60 //DEMORA ARTIFICIAL DA ATUALIZAÇÃO DO JOGO, EM MS

#define BLOCOS 3 //NUMERO DE BLOCOS QUE O DAVE SALTA

#define MAXCOLET 20 //MAXIMO DE COLETAVEIS EM UM MAPA

#define DIR_SAVE "Dados/jogo.bin" //DIRETÓRIO DO ARQUIVO DE SALVAMENTO

#endif