/*
    UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL
    INF01202 - ALGORITMOS E PROGRAMAÇÃO

    ATIVIDADE PRÁTICA
    TRABALHO FINAL DA DISCIPLINA

    ALUNOS: FELIPE GALLOIS E HENRIQUE CARNIEL DA SILVA
    MATRÍCULAS: 333713 E 335626

    ESTE PROGRAMA É UM JOGO INSPIRADO NO CLÁSSICO DOS ANOS 1980, DANGEROUS
    DAVE, E É PARTE DO TRABALHO FINAL DE AVALIAÇÃO DA DISCIPLINA DE ALGORITMOS
    E PROGRAMAÇÃO DO SEGUNDO SEMESTRE DE 2021.
*/

#ifndef CONSTANTES_H
#define CONSTANTES_H

enum estados {MENU, JOGO, RANKING}; /* POSSÍVEIS ESTADOS DO PROGRAMA */
enum botao {NOVO, CARREGAR, RANK, SAIR}; /* POSSÍVEIS SELEÇÕES NO MENU INICIAL */
enum teclas {INVALIDO, CIMA, BAIXO, DIREITA, ESQUERDA, ESC, S, N, SPCBR, ENTER}; /* POSSÍVEIS ENTRADAS DO USUÁRIO */

#define ESTADOINI MENU /* ESTADO EM QUE O PROGRAMA DEVE INICIAR */

#define VIDAS 5 /* VIDAS DO DAVE */

#define ALT_PLACAR 6 /* ALTURA DO PLACAR */

#define ALTMAX 30 /* ALTURA MÁXIMA DE UM MAPA */
#define LARGMAX 60 /* LARGURA MÁXIMA DE UM MAPA */

#define NUM_FASES 3 /* NÚMERO TOTAL DE FASES */

#define MAPA1 "Mapas/fase_1.txt" /* PRIMEIRO MAPA A SER ABERTO */
#define MAPA2 "Mapas/fase_2.txt" /* SEGUNDO MAPA A SER ABERTO */
#define MAPA3 "Mapas/fase_3.txt" /* TERCEIRO MAPA A SER ABERTO */

#define DELAY 60 /* DEMORA ARTIFICIAL DA ATUALIZAÇÃO DO JOGO, EM MS */

#define BLOCOS 3 /* NUMERO DE BLOCOS QUE O DAVE SALTA */

#define MAXCOLET 20 /* MAXIMO DE COLETAVEIS EM UM MAPA */

#define DIR_SAVE "Dados/jogo.bin" /* DIRETÓRIO DO ARQUIVO DE SALVAMENTO */

#define TAM_RANKING 5 /* TAMANHO DO VETOR DE RANKINGS */

#define FRANKING "Dados/ranking.txt" /* ARQUIVO TEXTO ONDE ESTÁ ARMAZENADO AS 5 MAIORES PONTUAÇÕES */

#endif
